
FROM ros2_cc_base
LABEL maintainer="Alberto Soragna asoragna at irobot dot com"

ENV TOOL_COMMIT "49719d5"

###### INSTALL RASPBIAN CROSS-COMPILATION REQUIREMENTS

# TODO: install the tools from
# https://github.com/raspberrypi/tools/archive/master.zip
# https://github.com/raspberrypi/tools/tarball/master
# wget -qO- https://github.com/raspberrypi/tools/tarball/master | tar xz - -C /tmp/raspberrypi-tools

# wget -qO- https://github.com/raspberrypi/tools/tarball/49719d5 | tar xz -C /tmp/

# download and install the Raspberry Pi toolchain
RUN apt update && apt-get install -y wget tar
RUN wget -qO- https://github.com/raspberrypi/tools/tarball/${TOOL_COMMIT} | tar xz -C /opt/
#ENV PATH="/opt/raspberrypi-tools-${TOOL_COMMIT}/arm-bcm2708/arm-linux-gnueabihf/bin:${PATH}"
ENV PATH="/opt/raspberrypi-tools-${TOOL_COMMIT}/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin:${PATH}"